name: Deploy Production CI/CD

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js &{{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 22.17.0
          cache: 'npm'
      - name: Create .env file
        run: echo "${{ secrets.ENV_PRODUCTION }}" > .env.production
      - run: npm install
      - run: npm run build
